2025-03-20 22:56:02,685 - root - INFO - Logging has been configured.
2025-03-20 22:56:02,727 - __main__ - INFO - Loaded config.json - Starting execution with id 80046256-6cfb-43d1-8e21-192e8390ce32
2025-03-20 22:56:02,728 - configuration_manager - INFO - Configuration: 
2025-03-20 22:56:02,729 - configuration_manager - INFO - * Runtime ASM model: SafetyEnforcerModel.asm
2025-03-20 22:56:02,730 - model_uploader - INFO - Enforcer initialized with domain: http://localhost:8080/
2025-03-20 22:56:02,731 - model_uploader - INFO - Runtime model: SafetyEnforcerModel.asm
2025-03-20 22:56:02,731 - model_uploader - INFO - 
2025-03-20 22:56:06,834 - model_uploader - ERROR - HTTP Request failed: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /upload-model (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021052644DD0>: Failed to establish a new connection: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione'))
2025-03-20 22:56:06,837 - model_uploader - ERROR - Failed to upload model or library: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /upload-model (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021052644DD0>: Failed to establish a new connection: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione'))
2025-03-20 22:56:06,838 - __main__ - ERROR - Failed to connect to the server - Executing the test runs WITHOUT the model
2025-03-20 22:56:06,839 - __main__ - INFO - --Starting new test run--
2025-03-20 22:56:06,839 - __main__ - INFO - --Executing new step--
2025-03-20 22:58:42,283 - __main__ - INFO - Test run completed in 155443.43ms:
2025-03-20 22:58:42,284 - __main__ - INFO - * Effective Duration: 0 simulation steps
2025-03-20 22:58:42,285 - __main__ - INFO - 
