2025-03-21 22:17:13,757 - root - INFO - Logging has been configured.
2025-03-21 22:17:13,855 - __main__ - INFO - Loaded config.json - Starting execution with id 20f8828d-6fd7-4fb6-901b-142efb180e1f
2025-03-21 22:17:13,855 - configuration_manager - INFO - Configuration: 
2025-03-21 22:17:13,855 - configuration_manager - INFO - * Runtime ASM model: SafetyEnforcerModel.asm
2025-03-21 22:17:13,863 - model_uploader - INFO - Model engine initialized with domain: http://localhost:8080/
2025-03-21 22:17:13,863 - model_uploader - INFO - Runtime model: SafetyEnforcerModel.asm
2025-03-21 22:17:13,864 - model_uploader - INFO - 
2025-03-21 22:17:17,992 - model_uploader - ERROR - HTTP Request failed: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /upload-model (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002860FD8AE10>: Failed to establish a new connection: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione'))
2025-03-21 22:17:17,998 - model_uploader - ERROR - Failed to upload model or library: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /upload-model (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002860FD8AE10>: Failed to establish a new connection: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione'))
2025-03-21 22:17:18,001 - __main__ - ERROR - Failed to connect to the server - Executing the test runs WITHOUT the model
2025-03-21 22:17:18,001 - __main__ - INFO - --Starting new test run--
2025-03-21 22:17:18,001 - __main__ - INFO - --Executing new step--
